name: haskell-conduit
version: 0.1.0.0
github: "dabliuw22/haskell-conduit"
license: BSD3
author: "Will Leyton"
maintainer: "wleylop22@gmail.com"
copyright: "2021 Will Leyton"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/dabliuw22/haskell-conduit#readme>

dependencies:
  - base >= 4.7 && < 5
  - async
  - bytestring >= 0.10.10 && < 0.11
  - bytestring-conversion >= 0.1 && < 0.3.2
  - conduit
  - conduit-concurrent-map
  - conduit-extra
  - directory
  - filepath
  - katip >= 0.1.0.0 && < 0.8.6.0
  - resourcet
  - stm-conduit
  - text

library:
  source-dirs: src

executables:
  haskell-conduit-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-conduit

tests:
  haskell-conduit-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-conduit
